//
// Created by Andreas Zinkl on 27.05.17.
//

#ifndef DT2017_ERRORHANDLING_H
#define DT2017_ERRORHANDLING_H

// ROUTEDRIVER - ERROR HANDLING
#define COULD_NOT_CALCULATE_ROUTE_ERROR 100
#define COULD_NOT_CALCULATE_DRIVECOMMAND_ERROR 101
#define ERROR_WHILE_ROUTECALC_INIT 102
#define ERROR_WHILE_DRIVECALC_INIT 103

// MAP - ERROR HANDLING
#define INDEX_OUT_OF_MAP_ERROR 201

// ROUTECALCULATION - ERROR HANDLING
#define PATH_FOUND_SUCCESSFULLY 300
#define NO_PATH_FOUND_ERROR 301

#endif //DT2017_ERRORHANDLING_H
