//
// Created by Andreas Zinkl on 27.05.17.
//

#ifndef DT2017_ERRORHANDLING_H
#define DT2017_ERRORHANDLING_H

// DEFINE IF THE ERROR CODES SHOULD BE PRINTED!!
#define PRINT_ERROR_CODE true

// GENERAL CODE
#define SUCCESS 1
#define ERROR_WHILE_SYSTEM_INITIALIZATION 10

// ROUTEDRIVER - ERROR HANDLING
#define COULD_NOT_CALCULATE_ROUTE_ERROR 100
#define COULD_NOT_CALCULATE_DRIVECOMMAND_ERROR 101
#define ERROR_WHILE_ROUTECALC_INIT 102
#define ERROR_WHILE_DRIVECALC_INIT 103
#define DROVEN_DISTANCE_IS_ZERO 104
#define DRIVECALCULATER_NOT_INITIALIZED 105
#define NO_DRIVING_COMMANDS_LEFT 106
#define NO_PREDICTED_POSITION_AVAILABLE 107
#define SKIP_CHECKING 108
#define NEW_COMMAND_NEEDED_EXECUTED 109
#define ROUTE_OBSTACLE_CROSSING 110

// MAP - ERROR HANDLING
#define INDEX_OUT_OF_MAP_ERROR 201

// ROUTECALCULATION - ERROR HANDLING
#define PATH_FOUND_SUCCESSFULLY 300
#define NO_PATH_FOUND_ERROR 301

#endif //DT2017_ERRORHANDLING_H
